version: '3.8'

# command to fetch docker hub's latest image
# docker pull nanachi1027/hql-fabric-example:latest
services:
  postgres:
    image: postgres:15
    container_name: hql_fabric_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hql_fabric_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

  hql-fabric-app:
    image: nanachi1027/hql-fabric-example:latest
    container_name: hql_fabric_example
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hql_fabric_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    restart: unless-stopped

volumes:
  pgdata: