version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: hql_fabric_test_db
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: hql_fabric_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata-test:/var/lib/postgresql-test/data

volumes:
  pgdata-test: