version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg15_hql_fabric
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hql_fabric_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: