name: Build HQL-Fabric Project

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5431:5432
        env:
          POSTGRES_DB: hql_fabric_test_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd="pg_isready -U admin -d hql_fabric_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5431 -U admin && break
            echo "Waiting for postgres..." && sleep 5
          done

      - name: Build with Maven
        run: |
          cd hql-fabric
          mvn clean install -DskipTests
