name: Build HQL-Fabric Project's Docker Images

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: hql_fabric_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd="pg_isready -U admin -d hql_fabric_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U admin && break
            echo "Waiting for postgres..." && sleep 5
          done

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push Docker Image for hql-fabric-example && push to remote docker hub 
        run: |
          mvn clean install 
          cd hql-fabric/hql-fabric-example
          mvn clean package -Pjib-push-to-dockerhub -Dapp.image.name=hql-fabric-example -Dapp.image.tag=latest
          echo "Built images (filter):"
          docker images | grep hql-fabric-example || echo "No hql-fabric-example image found"
